name: om_assessment
services:
  om_assessment-api_service:
    image: om_assessment-api_service
    container_name: om_assessment-api_service
    build:
      context: .
      dockerfile: OM.Assessment.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: '${ASPNETCORE_ENVIRONMENT:-Development}'
      ASPNETCORE_URLS: 'http://+:80'
    healthcheck:
      test: curl --fail http://om_assessment-api_service:80/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - '8003:80'
    networks:
      - om_assessment-net
    restart:
      always
    
  app:
    build:
      context: .
      dockerfile: om-assessment-web/Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    networks:
      - om_assessment-net
    restart: always

networks:
  om_assessment-net:
    driver: bridge
    
volumes:
  node_modules:

