name: om_assessment
services:
  postgres:
    image: postgres:latest
    container_name: om_assessment.postgresql
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Admin
    command: >
      postgres -c wal_level=logical -c max_wal_senders=5 -c max_replication_slots=5;done;
    ports:
      - '5432:5432'
    networks:
      - face-off-net
    volumes:
      - './scripts/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql'
    restart:
      on-failure

networks:
  face-off-net:
    driver: bridge

volumes:
  postgres:
  rabbitmq:
  redis_data:
